FROM debian:stretch

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=ratcoin/ratcoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
	git \
	sudo

#RUN git clone $REPO_URL --branch $BRANCH_NAME --single-branch --depth 1 

COPY ratcoin.tar.gz /ratcoin.tar.gz
RUN tar -xvf /ratcoin.tar.gz

RUN cd /ratcoin && ./scripts/dependencies-ubuntu.sh && ./scripts/install-ubuntu.sh && \
	apt-get purge git build-essential -qy && \
	apt-get autoremove -qy && \
	apt-get clean
